# E-Commerce Price Monitoring System - Scrapers Configuration
# Site-specific scraping configurations for Amazon and eBay

sites:
  amazon:
    name: "Amazon"
    base_url: "https://www.amazon.com"
    scraper_class: "AmazonScraper"
    scraper_type: "static"
    rate_limit: 2.0
    requires_selenium: false
    selectors:
      title: "#productTitle"
      price: ".a-price-whole, .a-price-fraction"
      price_symbol: ".a-price-symbol"
      availability: "#availability span"
      image: "#landingImage"
      rating: ".a-icon-alt"
      reviews_count: "#acrCustomerReviewText"
      brand: "#bylineInfo"
    headers:
      User-Agent: "Mozilla/5.0 (compatible; PriceMonitor/1.0)"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.5"
      Accept-Encoding: "gzip, deflate"
      DNT: "1"
      Connection: "keep-alive"
    
  ebay:
    name: "eBay"
    base_url: "https://www.ebay.com"
    scraper_class: "EbayScraper"
    scraper_type: "static"
    rate_limit: 3.0
    requires_selenium: false
    selectors:
      title: "h1[id='x-title-label-lbl'], .x-item-title__mainTitle, h1.it-ttl, h1"
      price: ".x-price-primary, .notranslate, .u-flL.notranslate, .x-price-approx__price"
      availability: ".u-flL.condText"
      image: "#icImg"
      condition: ".u-flL.condText"
      shipping: ".vi-price .notranslate"
      seller: ".mbg-nw"
      location: ".ux-textspans--SECONDARY"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.9"
      Accept-Encoding: "gzip, deflate, br"
      Sec-Ch-Ua: '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"'
      Sec-Ch-Ua-Mobile: "?0"
      Sec-Ch-Ua-Platform: '"Windows"'
      Sec-Fetch-Dest: "document"
      Sec-Fetch-Mode: "navigate"
      Sec-Fetch-Site: "none"
      Sec-Fetch-User: "?1"
      Upgrade-Insecure-Requests: "1"

  shopge:
    name: "Shop.ge"
    base_url: "https://www.shop.ge"
    scraper_class: "ShopGeScraper"
    scraper_type: "static"
    rate_limit: 1.5
    requires_selenium: false
    selectors:
      title: "h1"
      price: "span:contains('₾')"
      availability: "body"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  
  shop.ge:
    name: "Shop.ge"
    base_url: "https://www.shop.ge"
    scraper_class: "ShopGeScraper"
    scraper_type: "static"
    rate_limit: 1.5
    requires_selenium: false
    selectors:
      title: "h1"
      price: "span:contains('₾')"
      availability: "body"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Product categories and search configurations
product_categories:
  electronics:
    smartphones:
      keywords: ["iPhone", "Samsung Galaxy", "Google Pixel", "OnePlus", "Xiaomi"]
      min_price: 100
      max_price: 2000
      search_terms:
        amazon: ["smartphone", "mobile phone", "cell phone"]
        ebay: ["smartphone", "mobile phone"]
    laptops:
      keywords: ["MacBook", "ThinkPad", "Dell XPS", "HP Spectre", "Surface Laptop"]
      min_price: 500
      max_price: 3000
      search_terms:
        amazon: ["laptop", "notebook", "ultrabook"]
        ebay: ["laptop", "notebook"]
    tablets:
      keywords: ["iPad", "Surface", "Galaxy Tab", "Fire Tablet", "Lenovo Tab"]
      min_price: 100
      max_price: 1500
      search_terms:
        amazon: ["tablet", "ipad", "android tablet"]
        ebay: ["tablet", "ipad"]

# Scraping rules and compliance
scraping_rules:
  respect_robots_txt: true
  max_pages_per_session: 100
  session_cooldown: 300  # seconds
  error_threshold: 5  # max errors before stopping
  retry_delays: [1, 2, 4, 8, 16]  # exponential backoff in seconds
  
# Error handling configuration
error_handling:
  network_timeout: 30
  max_redirects: 5
  retry_on_status_codes: [429, 500, 502, 503, 504]
  skip_on_status_codes: [404, 403, 401]
  
# Data validation rules
validation:
  price:
    min_value: 0.01
    max_value: 10000.00
    currency_symbols: ["$", "USD", "€", "EUR", "£", "GBP"]
  title:
    min_length: 5
    max_length: 500
    required_fields: ["title"]
  availability:
    valid_statuses: ["in_stock", "out_of_stock", "limited", "unknown"]

# Sample product URLs for testing (replace with real URLs for production)
sample_products:
  smartphones:
    amazon:
      - "https://www.amazon.com/dp/B0863FR3S9"  # Sony headphones (working)
    ebay:
      - "https://www.ebay.com/itm/335930354247"  # Invicta watch (working)
  laptops:
    amazon:
      - "https://www.amazon.com/dp/B08N5WRWNW"  # MacBook example
    ebay:
      - "https://www.ebay.com/itm/123456789"    # ThinkPad example
  tablets:
    amazon:
      - "https://www.amazon.com/dp/B09G9FPHY6"  # iPad example
    ebay:
      - "https://www.ebay.com/itm/456789123"    # Surface example
    shopge:
      - "https://www.shop.ge/online-shop/sakancelario-nivtebi/saweri-kalami/troika-kalami-troika-construction-liliput-697455.html"